// Download the current (edited) artifacts as a versioned zip: the APIs.json, each API's OpenAPI
// (with the iteration-layer edits baked in), and the guide skill. The version lives in the folder
// path so successive downloads are self-describing snapshots you can diff.

import JSZip from 'jszip';
import { stringify as toYAML } from 'yaml';
import { getGuideSkill } from './guide';
import { downloadBlob } from './ui';
import type { ApisDoc } from './model';
import type { ExpApi } from './experience';

const slugify = (s: string) => String(s || 'apis').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'apis';

export async function downloadBundle(doc: ApisDoc, apis: ExpApi[], versionLabel: string): Promise<void> {
  const zip = new JSZip();
  const slug = slugify(doc.name);
  const root = `${slug}-${versionLabel}`;

  // Deep-clone the raw APIs.json so we can repoint each API's OpenAPI at the bundled copy.
  const apisJson = JSON.parse(JSON.stringify(doc.raw || {}));
  apisJson.modified = versionLabel;

  const rawApis = Array.isArray(apisJson.apis) ? apisJson.apis : [];
  apis.forEach((exp, i) => {
    if (!exp.oaDoc) return;
    const fname = `openapi/${slugify(exp.name)}-openapi.yml`;
    zip.file(`${root}/${fname}`, toYAML(exp.oaDoc));
    // Rewrite the matching API entry's OpenAPI property to the local file.
    const entry = rawApis[i];
    if (entry && Array.isArray(entry.properties)) {
      const oa = entry.properties.find((p: { type?: string }) => ['OpenAPI', 'Swagger', 'OpenAPISpec'].includes(p.type || ''));
      if (oa) { oa.url = `./${fname}`; delete oa.data; }
    }
  });

  zip.file(`${root}/apis.json`, JSON.stringify(apisJson, null, 2));
  zip.file(`${root}/skills/api-experience-guide/SKILL.md`, getGuideSkill());
  zip.file(`${root}/README.md`, readme(doc, apis, versionLabel));

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = `${root}.zip`;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

function readme(doc: ApisDoc, apis: ExpApi[], version: string): string {
  const ops = apis.reduce((n, a) => n + a.operations.length, 0);
  return `# ${doc.name} — API Experience bundle (${version})

Generated by API Experience (experience.apicommons.org).

- \`apis.json\` — the APIs.json descriptor (OpenAPI properties repointed to the bundled specs)
- \`openapi/\` — each API's OpenAPI, with iteration-layer edits (paths, x-tier, x-mcp-tool,
  x-agent-skill, and the x-apis-io prompts/resources map) baked in
- \`skills/api-experience-guide/SKILL.md\` — the guide skill that steered the suggestions

Surface: ${apis.length} API(s), ${ops} operation(s).
`;
}
